project:main.o add.o print_data.o count_nodes.o file.o reverse.o 
	cc main.o add.o print_data.o count_nodes.o file.o reverse.o -o project
main.o:main.c
	cc -c main.c -o main.o
add.o:add.c
	cc -c add.c -o add.o
print_data.o:print_data.c
	cc -c print_data.c -o print_data.o
count_nodes.o:count_nodes.c
	cc -c count_nodes.c -o count_nodes.o
file.o:file.c
	cc -c file.c -o file.o
reverse.o:reverse.c
	cc -c reverse.c -o reverse.o





